theme: minima
plugins:
  - jekyll-feed
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - tests/
   - test-reports/
collections:
  case_studies:
    output: true
