on: push
jobs:
  tests: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - run: make
    - run: make test
    - uses: actions/upload-artifact@v1
      with:
        name: pytest-results
        path: test-reports/test-results.xml
      if: ${{ always() }}
    - uses: AutoModality/action-xunit-viewer@v1  
      id: xunit-viewer
    - uses: actions/upload-artifact@v1
      with:
        name: ${{ steps.xunit-viewer.outputs.report-name }}
        path: ${{ steps.xunit-viewer.outputs.report-dir }}
